version: "3.4"

services:
  mongodb:
    image: mongo:4.2-bionic
    volumes:
      - mongodb_data:/data/db

  app:
    build: .
    ports:
      - 3000:3000
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_DB=app

volumes:
  mongodb_data:
